Update workflow_macos.yml
testing create manually

diff --git a/.github/workflows/workflow_macos.yml b/.github/workflows/workflow_macos.yml
--- a/.github/workflows/workflow_macos.yml
+++ b/.github/workflows/workflow_macos.yml
@@ -103,16 +103,24 @@ jobs:
             echo "No volume to unmount."
           fi
 
-      - name: Create Artifact
+#      - name: Create Artifact
+#        run: |
+#          cd toonz/build/toonz
+#          echo "Creating DMG..."
+#          if /usr/local/opt/qt@5/bin/macdeployqt OpenToonz.app -dmg -verbose=1; then
+#            echo "DMG created successfully."
+#          else
+#            echo "Failed to create DMG."
+#            exit 1
+#          fi
+
+      - name: Create DMG Manually
         run: |
-          cd toonz/build/toonz
-          echo "Creating DMG with hdiutil..."
-          if /usr/local/opt/qt@5/bin/macdeployqt OpenToonz.app -dmg -verbose=1; then
-            echo "DMG created successfully."
-          else
-            echo "Failed to create DMG with hdiutil."
-            exit 1
-          fi
+          mkdir -p /tmp/OpenToonz
+          cp -R toonz/build/toonz/OpenToonz.app /tmp/OpenToonz/
+          echo "Creating DMG from /tmp/OpenToonz..."
+          hdiutil create -volname "OpenToonz" -srcfolder /tmp/OpenToonz -format UDZO -o toonz/build/toonz/OpenToonz.dmg
+
 
       - uses: actions/upload-artifact@v4
         with:
