try force -x86_64

diff --git a/.github/workflows/workflow_macos.yml b/.github/workflows/workflow_macos.yml
--- a/.github/workflows/workflow_macos.yml
+++ b/.github/workflows/workflow_macos.yml
@@ -41,11 +41,19 @@ jobs:
 
       - name: Install libraries (force x86_64)
         run: |
-          INTEL_BREW="/usr/local/bin/brew"
-
+          # Detect Intel Homebrew path
+          if [ -x /usr/local/bin/brew ]; then
+            INTEL_BREW="/usr/local/bin/brew"
+          elif [ -x /opt/homebrew/bin/brew ]; then
+            INTEL_BREW="/opt/homebrew/bin/brew"
+          else
+            echo "Error: Homebrew not found in expected locations."
+            exit 1
+          fi
+          
           arch -x86_64 $INTEL_BREW update
           arch -x86_64 $INTEL_BREW cleanup
-
+          
           checkPkgAndInstall() {
             for pkg in "$@"; do
               if arch -x86_64 $INTEL_BREW list --versions $pkg > /dev/null 2>&1; then
@@ -57,9 +65,10 @@ jobs:
               fi
             done
           }
-
+          
           checkPkgAndInstall pkg-config glew lz4 libjpeg libpng lzo boost libusb libmypaint ccache jpeg-turbo ninja opencv openjph openexr qt@5
           arch -x86_64 $INTEL_BREW unlink qt || true
+
 
       - name: Set up cache
         run: |
