Update workflow_macos.yml

diff --git a/.github/workflows/workflow_macos.yml b/.github/workflows/workflow_macos.yml
--- a/.github/workflows/workflow_macos.yml
+++ b/.github/workflows/workflow_macos.yml
@@ -98,21 +98,22 @@ jobs:
       - name: Create Artifact
         run: |
           cd toonz/build/toonz
-          echo "Creating DMG..."
+          echo "Creating DMG..."    
           for ATTEMPT in {1..10}; do
             echo "Attempt $ATTEMPT to build DMG..."
-            /usr/local/opt/qt@5/bin/macdeployqt OpenToonz.app -dmg -verbose=0 && break
-            echo "DMG creation failed. Retrying in 10 seconds..."
-            sleep 10
+            /usr/local/opt/qt@5/bin/macdeployqt OpenToonz.app -dmg -verbose=0
+            
+            if [ -f OpenToonz.dmg ]; then
+              echo "DMG created successfully."
+              exit 0  # Exit if successful
+            fi
+            
+            echo "DMG creation failed. Retrying in 10 seconds..."  
+            sleep 10  
           done
 
-          # Verify if the DMG was created successfully
-          if [ ! -f OpenToonz.dmg ]; then
-            echo "Failed to create DMG after 10 attempts."
-            exit 1
-          fi
-
-          echo "DMG created successfully."
+          echo ">>> DMG file creation failed after 10 attempts. Aborting!"
+          exit 1  # Exit with failure status
 
       - uses: actions/upload-artifact@v4
         with:
